export default function Home() {
  return (
    <div className="min-h-screen flex items-center justify-center bg-gradient-to-br from-blue-50 to-indigo-100">
      <div className="text-center p-8">
        <h1 className="text-5xl font-bold text-gray-900 mb-4">AI Demo Shop</h1>
        <p className="text-xl text-gray-600 mb-8">Ready to be built by AI!</p>
        <div className="bg-white rounded-lg p-6 shadow-lg max-w-md mx-auto">
          <p className="text-sm text-gray-500">
            Ask the AI to create components, pages, and features.
            <br />Everything you see will be generated by AI.
          </p>
        </div>
      </div>
    </div>
  )
}